# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('desc', models.TextField(verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('desc', models.TextField(verbose_name='课程描述')),
                ('address', models.CharField(default='', max_length=100, verbose_name='机构地址')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('course_nums', models.IntegerField(default=0, verbose_name='课程数')),
                ('category', models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')], default='pxjg', max_length=20, verbose_name='机构类别')),
                ('image', models.ImageField(upload_to='media/org/image/%Y/%m', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.City', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '课程机构',
                'verbose_name_plural': '课程机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('work_years', models.IntegerField(default=1, verbose_name='工作年限')),
                ('work_position', models.CharField(default='', max_length=20, verbose_name='工作职位')),
                ('work_company', models.CharField(default='', max_length=20, verbose_name='就职公司')),
                ('points', models.TextField(blank=True, null=True, verbose_name='教学特点')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('course_nums', models.IntegerField(default=0, verbose_name='课程数')),
                ('image', models.ImageField(upload_to='media/org/teacher/%Y/%m', verbose_name='头像')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='课程机构')),
            ],
            options={
                'verbose_name': '机构讲师',
                'verbose_name_plural': '机构讲师',
            },
        ),
    ]
