# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '用户学习', 'verbose_name_plural': '用户学习'},
        ),
        migrations.AlterField(
            model_name='userfavourite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '机构'), (3, '教师')], max_length=10, verbose_name='类型'),
        ),
    ]
