# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20171110_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
