# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_click_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='后台开发', max_length=30, verbose_name='课程类别'),
        ),
    ]
