# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.CharField(choices=[('yes', '是'), ('no', '不是')], default='no', max_length=10, verbose_name='是否轮播图'),
        ),
    ]
