# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='media/users/banner/%Y/%m', verbose_name='图像'),
        ),
    ]
