# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171109_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/users/image/default_big_14.png', max_length=50, upload_to='media/users/image/%Y/%m', verbose_name='头像'),
        ),
    ]
